# Data sources

The data comes from the Centers for Disease Control and Prevention (CDC) and the link to the data is https://wonder.cdc.gov/cancer.html. The data was from The United States Cancer Statistics (USCS) which are the official federal statistics on cancer incidence from registries having high-quality data and cancer mortality statistics for 50 states and the District of Columbia. And USCS are produced by CDC and the National Cancer Institute (NCI). All of USCS contributors and partners are responsible for collecting this data. Since our data contains incidence data and mortality data, the incidence data are provided by The Centers for Disease Control and Prevention National Program of Cancer Registries (NPCR), The National Cancer Institute Surveillance, Epidemiology and End Results (SEER) program, and The Centers for Disease Control and Prevention National Vital Statistics System (NVSS). Cancer mortality data for deaths after 2018 are available from NVSS. There are several choices to request a data form, firstly we choose group results by leading cancer sites and by year, sex, race, and region, then choose measures to contain death counts and incidence counts. Secondly, we select locations by state. Finally, we choose data to contain all year, sex, race, and region.


This data contains some information about leading cancer sites, mortality-incidence rate which is age-adjusted, and patients’ personal information such as sex, race, region, and year of diagnosis. Among our dataset, Leading Cancer Sites, Year, Sex, Race, Region are categorical variables, and Mortality-Incidence Age-Adjusted Rate Ratio, Death Counts, Incidence Counts are continuous variables. The data contains 11264 observations.


Interestingly, we find that the death counts in some observations are 0, which means that no death in that observation, resulting in the morality-incidence rate ratio being not applicable.
